import 'dotenv/config';
export const PORT = process.env.PORT || 3000;
export const DATABASE_URL=process.env.DATABASE_URL||'';
export const Node_env=process.env.Node_env||'development';
export const slot_Days=Number(process.env.slot_generationDays)||30;
export const Temporal_Address=process.env.Temporal_Address||'http://localhost:7233';
export const Temporal_namespace=process.env.Temporal_namespace||'default';
export const Temporal_taskqueue=process.env.Temporal_taskqueue||'calendly_task';
export const Temporal_enabled='true';
export const SMTP_Host=process.env.SMTP_Host||'localhost';
export const SMTP_Port=Number(process.env.SMTP_Port)||1025;
export const SMTP_User=process.env.SMTP_User||'';
export const SMTP_Password=process.env.SMTP_Password||'';
export const Email_From=process.env.Email_From||'Calendly <no-reply@calendly.com>';