import { Router } from "express";
import { validate } from '../middlewares/validate.js';
import { requireUserId } from '../middlewares/require_user_id.js';
import { add_event, list_user_events, delete_event, patch_event, get_event_byID_controller } from "../controllers/event.controller.js";
import { create_eventScema, update_eventScema } from "../dtos/event_dto.js";
export const event_Router=Router();
event_Router.post('/', requireUserId, validate(create_eventScema), add_event);
event_Router.get('/', requireUserId, list_user_events);
event_Router.patch('/:event_id', requireUserId, validate(update_eventScema), patch_event);
event_Router.delete('/:event_id', requireUserId, delete_event);
event_Router.get('/:event_id', get_event_byID_controller);